version: '3.8'

services:
  signal-cli:
    image: bbernhard/signal-cli-rest-api
    container_name: signal-cli-rest-api
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - /opt/signal-cli-data:/home/.local/share/signal-cli
    environment:
      - MODE=json-rpc
