import { Router } from 'express';
import weatherRouter from './weather.js';
import webcamsRouter from './webcams.js';
import trafficRouter from './traffic.js';
import searchRouter from './search.js';
import aiRouter from './ai.js';
import stateRouter from './state.js';
import tilesRouter from './tiles.js';
import routeRouter from './route.js';
import authRouter from './auth.js';
import adminRouter from './admin.js';
import projectsRouter from './projects.js';
import groupsRouter from './groups.js';
import streetviewRouter from './streetview.js';
import avalancheWarningsRouter from './avalanche-warnings.js';
import aircraftRouter from './aircraft.js';
import aisRouter from './ais.js';
import themesRouter from './themes.js';
import timelapseRouter from './timelapse.js';
import auroraRouter from './aurora.js';
import monitoringRouter from './monitoring.js';
import wasosRouter from './wasos.js';
import nvdbRouter from './nvdb.js';
import infrastructureRouter from './infrastructure.js';
import superAdminRouter from './super-admin.js';
import sharesRouter from './shares.js';
import upscaleRouter from './upscale.js';
import signalRouter from './signal.js';
import viewshedRouter from './viewshed.js';
import rfcoverageRouter from './rfcoverage.js';
import firingRangeRouter from './firing-range.js';
import vulnerabilityRouter from './vulnerability.js';
const router = Router();

router.use('/weather', weatherRouter);
router.use('/webcams', webcamsRouter);
router.use('/traffic', trafficRouter);
router.use('/search', searchRouter);
router.use('/ai', aiRouter);
router.use('/state', stateRouter);
router.use('/tiles', tilesRouter);
router.use('/route', routeRouter);
router.use('/auth', authRouter);
router.use('/admin', adminRouter);
router.use('/projects', projectsRouter);
router.use('/groups', groupsRouter);
router.use('/streetview', streetviewRouter);
router.use('/avalanche-warnings', avalancheWarningsRouter);
router.use('/aircraft', aircraftRouter);
router.use('/ais', aisRouter);
router.use('/themes', themesRouter);
router.use('/timelapse', timelapseRouter);
router.use('/aurora', auroraRouter);
router.use('/monitoring', monitoringRouter);
router.use('/wasos', wasosRouter);
router.use('/nvdb', nvdbRouter);
router.use('/infrastructure', infrastructureRouter);
router.use('/super-admin', superAdminRouter);
router.use('/share', sharesRouter);
router.use('/upscale', upscaleRouter);
router.use('/signal', signalRouter);
router.use('/viewshed', viewshedRouter);
router.use('/rfcoverage', rfcoverageRouter);
router.use('/firing-range', firingRangeRouter);
router.use('/vulnerability', vulnerabilityRouter);
export default router;
