const labels = {
  no: {
    clearsky: 'Klarvær',
    fair: 'Lettskyet',
    partlycloudy: 'Delvis skyet',
    cloudy: 'Overskyet',
    rain: 'Regn',
    lightrain: 'Lett regn',
    heavyrain: 'Kraftig regn',
    rainshowers: 'Regnbyger',
    lightrainshowers: 'Lette regnbyger',
    heavyrainshowers: 'Kraftige regnbyger',
    snow: 'Snø',
    lightsnow: 'Lett snø',
    heavysnow: 'Kraftig snøfall',
    snowshowers: 'Snøbyger',
    lightsnowshowers: 'Lette snøbyger',
    heavysnowshowers: 'Kraftige snøbyger',
    sleet: 'Sludd',
    sleetshowers: 'Sluddbyger',
    lightsleet: 'Lett sludd',
    heavysleet: 'Kraftig sludd',
    lightsleetshowers: 'Lette sluddbyger',
    heavysleetshowers: 'Kraftige sluddbyger',
    fog: 'Tåke',
    rainandthunder: 'Torden og regn',
    snowandthunder: 'Torden og snø',
    sleetandthunder: 'Torden og sludd',
    lightrainandthunder: 'Lett regn og torden',
    heavyrainandthunder: 'Kraftig regn og torden',
    lightsnowandthunder: 'Lett snø og torden',
    heavysnowandthunder: 'Kraftig snø og torden',
    lightrainshowersandthunder: 'Lette regnbyger og torden',
    heavyrainshowersandthunder: 'Kraftige regnbyger og torden',
    lightsnowshowersandthunder: 'Lette snøbyger og torden',
    heavysnowshowersandthunder: 'Kraftige snøbyger og torden',
    lightsleetandthunder: 'Lett sludd og torden',
    heavysleetandthunder: 'Kraftig sludd og torden',
    rainshowersandthunder: 'Regnbyger og torden',
    snowshowersandthunder: 'Snøbyger og torden',
    sleetshowersandthunder: 'Sluddbyger og torden',
    lightssleetshowersandthunder: 'Lette sluddbyger og torden',
    heavysleetshowersandthunder: 'Kraftige sluddbyger og torden',
  },
  en: {
    clearsky: 'Clear sky',
    fair: 'Fair',
    partlycloudy: 'Partly cloudy',
    cloudy: 'Cloudy',
    rain: 'Rain',
    lightrain: 'Light rain',
    heavyrain: 'Heavy rain',
    rainshowers: 'Rain showers',
    lightrainshowers: 'Light rain showers',
    heavyrainshowers: 'Heavy rain showers',
    snow: 'Snow',
    lightsnow: 'Light snow',
    heavysnow: 'Heavy snow',
    snowshowers: 'Snow showers',
    lightsnowshowers: 'Light snow showers',
    heavysnowshowers: 'Heavy snow showers',
    sleet: 'Sleet',
    sleetshowers: 'Sleet showers',
    lightsleet: 'Light sleet',
    heavysleet: 'Heavy sleet',
    lightsleetshowers: 'Light sleet showers',
    heavysleetshowers: 'Heavy sleet showers',
    fog: 'Fog',
    rainandthunder: 'Rain and thunder',
    snowandthunder: 'Snow and thunder',
    sleetandthunder: 'Sleet and thunder',
    lightrainandthunder: 'Light rain and thunder',
    heavyrainandthunder: 'Heavy rain and thunder',
    lightsnowandthunder: 'Light snow and thunder',
    heavysnowandthunder: 'Heavy snow and thunder',
    lightrainshowersandthunder: 'Light rain showers and thunder',
    heavyrainshowersandthunder: 'Heavy rain showers and thunder',
    lightsnowshowersandthunder: 'Light snow showers and thunder',
    heavysnowshowersandthunder: 'Heavy snow showers and thunder',
    lightsleetandthunder: 'Light sleet and thunder',
    heavysleetandthunder: 'Heavy sleet and thunder',
    rainshowersandthunder: 'Rain showers and thunder',
    snowshowersandthunder: 'Snow showers and thunder',
    sleetshowersandthunder: 'Sleet showers and thunder',
    lightssleetshowersandthunder: 'Light sleet showers and thunder',
    heavysleetshowersandthunder: 'Heavy sleet showers and thunder',
  },
};

export function getWeatherLabel(symbolCode, lang = 'no') {
  if (!symbolCode) return '?';
  const code = symbolCode.replace(/_day|_night|_polartwilight/g, '');
  return labels[lang]?.[code] || labels.en[code] || code;
}
